version: 2.1

executors:
  shell-executor:
    docker:
      - image: circleci/node:14

workflows:
  version: 2
  workflow:
    jobs:
      - manual-job:
          filters:
            branches:
              ignore: /.*/
      - auto-job:
          filters:
            branches:
              only: main

jobs:
  manual-job:
    executor: shell-executor
    steps:
      - checkout
      - run:
          name: Manual Job
          command: |
            echo "Manual"

  auto-job:
    executor: shell-executor
    steps:
      - checkout
      - run:
          name: Auto Job
          command: |
            echo "Branch name: ${CIRCLE_BRANCH}"
