version: 2.1

workflows:
  version: 2
  workflow:
    jobs:
      - manual-job
      - auto-job:
          requires:
            - manual-job

jobs:
  manual-job:
    executor: shell
    steps:
      - checkout
      - run:
          name: Manual Job
          command: |
            echo "Manual"

  auto-job:
    executor: shell
    filters:
      branches:
        only: main
    steps:
      - checkout
      - run:
          name: Auto Job
          command: |
            echo "Auto"
